### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by pmuens** [JustServerless/discuss#12]
This is a good implementation: https://github.com/jimpick/lambda-comments/blob/master/packages/frontend/src/ui/comment.js

**Comment by xndrdev** [comment]
What about: https://github.com/rexxars/react-markdown ? @pmuens

**Comment by pmuens** [comment]
I would like to go with those `MarkdownIt` and `highlight.js`. They play nicely together:

Here you can see their usage:
https://github.com/jimpick/lambda-comments/blob/master/packages/frontend/src/ui/comment.js#L4
https://github.com/jimpick/lambda-comments/blob/master/packages/frontend/src/ui/comment.js#L16-L32
https://github.com/jimpick/lambda-comments/blob/master/packages/frontend/src/ui/comment.js#L43

**Comment by xndrdev** [comment]
Ok! I take a look on it and send you a PR.

**Comment by pmuens** [comment]
Great! Thank you! I'll assign you.
