### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by xndrdev** [JustServerless/discuss#19]
What about if we add an **edit** button for the inline editing? 

It's sometimes to _dangerous_, if you want to copy something or maybe click by accident. I think it's also better for the UX, if people see that there is a an **edit** button.

What do you think @pmuens ?

Would add a button **Edit**. If you click the button the content gets an textarea. Basically the same behaviour but only with a click on edit.

**Comment by pmuens** [comment]
Good catch! I was also thinking about smth. similar before --> 👍

**Comment by xndrdev** [comment]
FYI: There were some issues in #12. So i will at first close this issue before going on with #12. @pmuens

**Comment by pmuens** [comment]
Alright. Thank you for the quick update. Just go ahead and ping me once I can review! 👍
