### ISSUE TITLE
Add Gravatar support

### ISSUE THREAD

**Issue by pmuens** [JustServerless/discuss#7]
Add the users Gravatar on the left hand side of the post / comment.

**Comment by xndrdev** [comment]
I would use https://github.com/KyleAMathews/react-gravatar and add gravatar support for the users.

**Comment by pmuens** [comment]
Yep. The other thing we need to discuss is the problem that we then have the users E-Mail address in the Redux store on the client (which means that it's exposed to the world).

**Comment by xndrdev** [comment]
What if we use something like https://github.com/emerleite/node-gravatar ? 

Or maybe this is helpful: http://nodeexamples.com/2013/09/04/creating-an-md5-hash-to-get-profile-images-from-gravatar/

I think we should not expose the email of the user and calculate the hash for gravatar on the server. @pmuens

**Comment by pmuens** [comment]
Yes. Computing that backend wise would be good.
